"""make db complaint id required

Revision ID: 61da14a253e8
Revises: eb3be35da76f
Create Date: 2024-01-24 21:51:25.098990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61da14a253e8'
down_revision = 'eb3be35da76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
